version: '3.8'

services:
  learning:
    build: .
    container_name: learning
    ports:
      - "8080:8888"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=dockerdb
      - MYSQL_USER=dockerdb
      - MYSQL_PASSWORD=dockerdb
    volumes:
      - ./mysql_data:/var/lib/mysql

  mysql:
    container_name: mysql
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dockerdb
      - MYSQL_USER=dockerdb
      - MYSQL_PASSWORD=dockerdb
    volumes:
      - ./mysql_data:/var/lib/mysql
