version: '8.2'

services:
  mysql:
    container_name: mysql
    image: mysql:8.2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dockerdb
      - MYSQL_USER=dockerdb
      - MYSQL_PASSWORD=dockerdb
    volumes:
      - ./mysql_data:/var/lib/mysql